name = "soccer-fantasy"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "soccer-fantasy"

[[routes]]
pattern = "www.garageapothecary.com/soccer-fantasy*"
zone_name = "garageapothecary.com"

[[routes]]
pattern = "garageapothecary.com/soccer-fantasy*"
zone_name = "garageapothecary.com"
